jobs:
  build:
    container:
      image: mcr.microsoft.com/openjdk/jdk:${{ matrix.java }}
      options: --user root
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      run: ./gradlew check build publishToMavenLocal --stacktrace
    - continue-on-error: true
      if: ${{ failure() }}
      uses: Juuxel/publish-checkstyle-report@v1
      with:
        reports: '**/build/reports/checkstyle/*.xml

          '
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts ${{ matrix.java }}
        path: 'build/libs/

          ./*/build/libs/

          build/publishMods/

          '
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: Maven Local ${{ matrix.java }}
        path: /root/.m2/repository/net/fabricmc/
    strategy:
      matrix:
        java:
        - 21-ubuntu
  check_resources:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: microsoft
        java-version: '21'
    - continue-on-error: true
      run: ./gradlew generateResources --stacktrace --warning-mode=fail
    - continue-on-error: true
      run: if [ -n "$(git status --porcelain)" ]; then exit 1; fi
  client_test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: microsoft
        java-version: '21'
    - continue-on-error: true
      name: Run Auto test Client
      uses: modmuss50/xvfb-action@v1
      with:
        run: ./gradlew runProductionAutoTestClient --stacktrace --warning-mode=fail
    - continue-on-error: true
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Screenshots
        path: run/screenshots
  server_test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: microsoft
        java-version: '21'
    - continue-on-error: true
      run: mkdir run && echo "eula=true" >> run/eula.txt
    - continue-on-error: true
      run: ./gradlew runProductionAutoTestServer --stacktrace --warning-mode=fail
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
