jobs:
  labels:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: FabricMC/fabric-action-scripts@v2
      with:
        context: ${{ github.event.action }}
        label: ${{ github.event.label.name }}
name: Manage Issues
on:
  repository_dispatch:
    types: trigger-ga___manage_issues.yml
