jobs:
  build:
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: apt update && apt install git -y && git --version
    - continue-on-error: true
      run: git config --global --add safe.directory /__w/fabric/fabric
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: changelog
      uses: FabricMC/fabric-action-scripts@v2
      with:
        context: changelog
        workflow_id: release.yml
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      env:
        CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_URL: ${{ secrets.MAVEN_URL }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        SIGNING_JAR_KEY: ${{ secrets.SIGNING_JAR_KEY }}
        SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
        SIGNING_SERVER: ${{ secrets.SIGNING_SERVER }}
      run: ./gradlew checkVersion build publish publishMods --stacktrace
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
permissions:
  contents: write
